=== SeanHoey/assassinsCreed/web/WEB-INF/assassinscreed.xsd
<?xml version="1.0"?>
<!--Author: Sean Hoey x11000759 -->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
<xs:element name="assassinsCreed">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="game" type="xs:string"/>
      <xs:element name="intro" type="xs:string"/>
      <xs:element name="AC" type="xs:string"/>
      <xs:element name="h" type="xs:string"/>
      <xs:element name="image1"/>
      <xs:element name="image2"/>
      <xs:element name="image3"/>
      <xs:element name="image4"/>
      <xs:element name="image5"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="game">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="name" type="string"/>
      <xs:element name="intro" type="xs:string"/>
      <xs:element name="AC" type="xs:string"/>
      <xs:element name="image1"/>
      <xs:element name="image2"/>
      <xs:element name="image3"/>
      <xs:element name="image4"/>
      <xs:element name="image5"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>



1</xs:schema>

=== SeanHoey/assassinsCreed/web/WEB-INF/assassinsCreed3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="stylesheet.xsl" type="text/xsl"?>
<!--Author: Sean Hoey x11000759 -->
<assassinsCreed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='assassinscreed.xsd'>


<body>
    <name>Assassin's creed 3</name>
    <image5/>
    <intro>Assassin's Creed III is a sandbox style action-adventure video game that is developed by Ubisoft Montreal and published by Ubisoft. It is the fifth main title in the Assassin's Creed series, and is a direct sequel to Assassin's Creed: Revelations. Ubisoft has claimed that the game will be bigger than its previous installments, and will complete the story of Desmond Miles.The game is set between 1753 and 1783, and focuses on a new ancestor, Ratonhnhaké:ton also known as connor, who fought during the American Revolution.</intro>
    
    <h>plot</h>
    <AC>After the events of Assassin's Creed: Revelations on October 31, 2012, Desmond, his father William, Rebecca, and Shaun find the Temple in a cave in New York. Using the Apple to access the structure, Desmond activates a large portion of the equipment, as well as an apparent timer to the event expected on December 21, 2012. He then falls into a fugue, at which point he is returned to the Animus and bleeds back to Haytham Kenway, father to Connor. After playing as Haytham we start playing as connor from a young age as he grows up to learn to fight to defeat the templars schemes and protect his people.</AC>
    
    <h>Gameplay</h>
    <AC>Exploration will be based around a large countryside area known as the Frontier, which is one and a half times larger than Rome in Assassin's Creed: Brotherhood, and not as empty as the Kingdom in Assassin's Creed, as one third of the quests and gameplay content are contained there. The cities of Boston and New York may also be explored, and will have new details and ambiance</AC>
    <AC>More varied methods of movement have been added as well, including climbing trees, cliffs, and other natural elements, alongside leaping over wagons, or sliding under obstacles. Other freerunning elements also have Ratonhnhaké:ton jumping through windows, to trees, and then onto rooftops.</AC>
    
    <h>Combat</h>
    <AC>Dual-wielding weapons has been implemented, while fighting and stealth have been completely overhauled with new features, such as "double-counters," "multiple takedowns," and chain kills. Ratonhnhaké:ton will go into battle with a wide variety of weapons at his disposal, including two Hidden Blades, a tomahawk, flintlock pistols, rope darts, and a bow and arrow. Ratonhnhaké:ton's second Hidden Blade is able to be ejected and used as a dagger, of which it can also be used to skin hunted animals. </AC>
    <AC>The combat system has been greatly improved, as there are thousands of new animations, few of which have been carried over from previous installments. Simple defense and counter-attacks are now more difficult, and combat has been focused on putting Ratonhnhaké:ton on the offensive, with attacks based on both speed and momentum.</AC>
    
    <h>Hunting</h>
    <AC>Ratonhnhaké:ton can now hunt animals, enabling him to sell the resources gathered from them. These resources can be more valuable depending on quality of the kill performed on the animal, and on the weapon type used to kill it. </AC>
    
    <h>Homestead</h>
    <AC>Along with this, a new property system known as the Homestead will be added, in which Ratonhnhaké:ton will live in a manor with surrounding land, to which he can also invite other citizens to stay nearby. Here, the inhabitants will be given a second chance following the events of the war of the American Revolution, and will generate income through trade and crafting. Following this, the Homestead will expand with every resident that inhabits the area. </AC>
    
    </body>

</assassinsCreed>

=== SeanHoey/assassinsCreed/web/WEB-INF/assassinsCreedR.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="stylesheet.xsl" type="text/xsl"?>
<!--Author: Sean Hoey x11000759 -->
<assassinsCreed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='assassinscreed.xsd'>

    
    
<body> 
<name>Assassins Creed Revelations</name>
<image4/>
    <intro>
        Assassin's Creed: Revelations is a game published by Ubisoft and was developed by its subsidiary, Ubisoft Montreal. A direct sequel and follow-up to 2010's Assassin's Creed: Brotherhood, Revelations is the fourth main installment of the series.
    </intro>
    <h>Plot</h>
    <h>Modern day</h>
    <AC>Present-day protagonist Desmond Miles had fallen into a coma from the previous events of the previous games, and to save Desmond's mind, the Assassins had put him into a specialized safe area of the Animus, called The Black Room. Upon awakening inside the Animus, Desmond met the consciousness of Subject 16, who occupied the Animus before him. Sixteen explained that Desmond's mind was fragmented, and that the only way for him to separate the pieces of himself from those of his ancestors was to continue to play out their stories until there was nothing left for them to show Desmond, known as a Synch Nexus. Once he reached that point, the Animus would be able to separate the three individual's memories.</AC>
    <h>Past</h>
    <AC>Desmond entered the Black Room's memory corridor, which once again placed him in the perspective of Ezio Auditore. Ezio had traveled to Masyaf to attempt to unlock the secrets that Altaïr Ibn-La'Ahad had previously discovered and to find his true purpose in the struggle between the Assassins and the Templars. Upon arriving, he found the stronghold overrun by the Templars, who captured him and planned his execution.</AC>
    <AC>Ezio escaped to the bowels of the fortress where he discovered the entrance to Altaïr's library. He learned that five keys were required to unlock the door, that the Templars had the first, and that Niccolò Polo's journal would lead them to the rest. Ezio pursued a Templar captain, Leandros, to the Atlas village and recovered the journal from him. He learned that the remaining keys lie hidden in Constantinople, and that the Templars hoped to find the location of the Grand Temple in the library.</AC>
    <AC>Upon arriving in Constantinople, Ezio was greeted by Yusuf Tazim, the leader of the local Assassins Guild, and befriended a young student. While searching for Niccolò 's old trading post, Ezio came across and befriended Sofia Sartor, a young Italian traveler and book collector, and quickly became infatuated with her. Having recovered his first key and an encoded map from the Yerebatan Cistern, which would lead Ezio to the keys, he learned that each one was encoded with Altaïr's memories. Each key allowed Ezio to have an Animus-like experience in which he relived key moments of Altaïr's life.</AC>
    <h>Gameplay</h>
    <AC>The gameplay system from Assassin's Creed: Brotherhood was the basis for Revelations, though Ezio's free-running and combat skills had been upgraded with new features. Recruits and Desmond gameplay had been further expanded, though not all desired features were implemented, as the developer interviews indicated.</AC>
    <h>Hookblade</h>
    <AC>One of the primary new features was the Hookblade. An extension to the usual Hidden Blade in combat, the Hookblade allowed for grappling, throws, and new evasive maneuvers. Outside of combat, the Hookblade accelerated climbing and allowed Ezio to make use of the Ziplines placed around Constantinople.</AC>
    <h>Bombs</h>
    <AC>Also new to Revelations were Bombs, which required a component-based crafting system, allowing Ezio to make bombs for any purpose to aid in his missions.</AC>
    <h>Eagle vision</h>
    <AC>Eagle vision had been modified into Eagle Sense, which could allow the player to focus on a character and determine the route they had taken. This would thus give the player an estimation of where they would go, which would be useful for ambushes or locating a secluded place to strike a target. Also, when a custom marker was set, using Eagle Sense to trace it would show a pillar of light that disappeared when Ezio got within a certain distance of it.</AC>
    <h>Recruits</h>
    <AC>The Assassin recruit system had also been altered. While recruiting process had been expanded with new mission types, seven recruits could also be raised to a rank that allowed them to become masters of Assassin Dens. Recruiting missions had also been revamped to be far more detailed than before, requiring Ezio to aid citizens or complete a race challenge before the recruit joined Ezio's cause.</AC>
</body>
</assassinsCreed>
